export interface HanziWord {
  hanzi: string
  pinyin: string
}

export type HSKLevel = 1 | 2 | 3 | 4

export const hskLevelInfo: Record<HSKLevel, { name: string; description: string; wordCount: number }> = {
  1: { name: "HSK 1", description: "Beginner - Basic words and phrases", wordCount: 150 },
  2: { name: "HSK 2", description: "Elementary - Daily conversations", wordCount: 150 },
  3: { name: "HSK 3", description: "Intermediate - General topics", wordCount: 300 },
  4: { name: "HSK 4", description: "Upper Intermediate - Complex discussions", wordCount: 600 },
}

// HSK 1 Vocabulary (150 words)
export const hsk1Words: HanziWord[] = [
  { hanzi: "我", pinyin: "wǒ" },
  { hanzi: "你", pinyin: "nǐ" },
  { hanzi: "他", pinyin: "tā" },
  { hanzi: "她", pinyin: "tā" },
  { hanzi: "好", pinyin: "hǎo" },
  { hanzi: "是", pinyin: "shì" },
  { hanzi: "的", pinyin: "de" },
  { hanzi: "了", pinyin: "le" },
  { hanzi: "在", pinyin: "zài" },
  { hanzi: "有", pinyin: "yǒu" },
  { hanzi: "不", pinyin: "bù" },
  { hanzi: "人", pinyin: "rén" },
  { hanzi: "这", pinyin: "zhè" },
  { hanzi: "中", pinyin: "zhōng" },
  { hanzi: "大", pinyin: "dà" },
  { hanzi: "来", pinyin: "lái" },
  { hanzi: "上", pinyin: "shàng" },
  { hanzi: "国", pinyin: "guó" },
  { hanzi: "个", pinyin: "gè" },
  { hanzi: "到", pinyin: "dào" },
  { hanzi: "说", pinyin: "shuō" },
  { hanzi: "们", pinyin: "men" },
  { hanzi: "为", pinyin: "wèi" },
  { hanzi: "子", pinyin: "zǐ" },
  { hanzi: "和", pinyin: "hé" },
  { hanzi: "地", pinyin: "dì" },
  { hanzi: "出", pinyin: "chū" },
  { hanzi: "也", pinyin: "yě" },
  { hanzi: "时", pinyin: "shí" },
  { hanzi: "年", pinyin: "nián" },
  { hanzi: "得", pinyin: "de" },
  { hanzi: "就", pinyin: "jiù" },
  { hanzi: "那", pinyin: "nà" },
  { hanzi: "要", pinyin: "yào" },
  { hanzi: "下", pinyin: "xià" },
  { hanzi: "以", pinyin: "yǐ" },
  { hanzi: "会", pinyin: "huì" },
  { hanzi: "去", pinyin: "qù" },
  { hanzi: "过", pinyin: "guò" },
  { hanzi: "家", pinyin: "jiā" },
  { hanzi: "学", pinyin: "xué" },
  { hanzi: "对", pinyin: "duì" },
  { hanzi: "可", pinyin: "kě" },
  { hanzi: "里", pinyin: "lǐ" },
  { hanzi: "后", pinyin: "hòu" },
  { hanzi: "小", pinyin: "xiǎo" },
  { hanzi: "么", pinyin: "me" },
  { hanzi: "心", pinyin: "xīn" },
  { hanzi: "多", pinyin: "duō" },
  { hanzi: "天", pinyin: "tiān" },
  { hanzi: "能", pinyin: "néng" },
  { hanzi: "都", pinyin: "dōu" },
  { hanzi: "没", pinyin: "méi" },
  { hanzi: "日", pinyin: "rì" },
  { hanzi: "起", pinyin: "qǐ" },
  { hanzi: "还", pinyin: "hái" },
  { hanzi: "事", pinyin: "shì" },
  { hanzi: "只", pinyin: "zhǐ" },
  { hanzi: "想", pinyin: "xiǎng" },
  { hanzi: "看", pinyin: "kàn" },
  { hanzi: "开", pinyin: "kāi" },
  { hanzi: "手", pinyin: "shǒu" },
  { hanzi: "十", pinyin: "shí" },
  { hanzi: "用", pinyin: "yòng" },
  { hanzi: "前", pinyin: "qián" },
  { hanzi: "本", pinyin: "běn" },
  { hanzi: "见", pinyin: "jiàn" },
  { hanzi: "头", pinyin: "tóu" },
  { hanzi: "面", pinyin: "miàn" },
  { hanzi: "同", pinyin: "tóng" },
  { hanzi: "三", pinyin: "sān" },
  { hanzi: "老", pinyin: "lǎo" },
  { hanzi: "两", pinyin: "liǎng" },
  { hanzi: "长", pinyin: "cháng" },
  { hanzi: "知", pinyin: "zhī" },
  { hanzi: "样", pinyin: "yàng" },
  { hanzi: "现", pinyin: "xiàn" },
  { hanzi: "分", pinyin: "fēn" },
  { hanzi: "外", pinyin: "wài" },
  { hanzi: "些", pinyin: "xiē" },
  { hanzi: "高", pinyin: "gāo" },
  { hanzi: "把", pinyin: "bǎ" },
  { hanzi: "回", pinyin: "huí" },
  { hanzi: "二", pinyin: "èr" },
  { hanzi: "点", pinyin: "diǎn" },
  { hanzi: "月", pinyin: "yuè" },
  { hanzi: "明", pinyin: "míng" },
  { hanzi: "话", pinyin: "huà" },
  { hanzi: "儿", pinyin: "ér" },
  { hanzi: "名", pinyin: "míng" },
  { hanzi: "一", pinyin: "yī" },
  { hanzi: "四", pinyin: "sì" },
  { hanzi: "五", pinyin: "wǔ" },
  { hanzi: "六", pinyin: "liù" },
  { hanzi: "七", pinyin: "qī" },
  { hanzi: "八", pinyin: "bā" },
  { hanzi: "九", pinyin: "jiǔ" },
  { hanzi: "零", pinyin: "líng" },
  { hanzi: "今", pinyin: "jīn" },
  { hanzi: "很", pinyin: "hěn" },
  { hanzi: "太", pinyin: "tài" },
  { hanzi: "什", pinyin: "shén" },
  { hanzi: "谁", pinyin: "shuí" },
  { hanzi: "哪", pinyin: "nǎ" },
  { hanzi: "几", pinyin: "jǐ" },
  { hanzi: "怎", pinyin: "zěn" },
  { hanzi: "喜", pinyin: "xǐ" },
  { hanzi: "欢", pinyin: "huān" },
  { hanzi: "爱", pinyin: "ài" },
  { hanzi: "吃", pinyin: "chī" },
  { hanzi: "喝", pinyin: "hē" },
  { hanzi: "睡", pinyin: "shuì" },
  { hanzi: "觉", pinyin: "jiào" },
  { hanzi: "做", pinyin: "zuò" },
  { hanzi: "买", pinyin: "mǎi" },
  { hanzi: "写", pinyin: "xiě" },
  { hanzi: "读", pinyin: "dú" },
  { hanzi: "听", pinyin: "tīng" },
  { hanzi: "住", pinyin: "zhù" },
  { hanzi: "坐", pinyin: "zuò" },
  { hanzi: "站", pinyin: "zhàn" },
  { hanzi: "走", pinyin: "zǒu" },
  { hanzi: "跑", pinyin: "pǎo" },
  { hanzi: "叫", pinyin: "jiào" },
  { hanzi: "请", pinyin: "qǐng" },
  { hanzi: "谢", pinyin: "xiè" },
  { hanzi: "再", pinyin: "zài" },
  { hanzi: "书", pinyin: "shū" },
  { hanzi: "字", pinyin: "zì" },
  { hanzi: "朋", pinyin: "péng" },
  { hanzi: "友", pinyin: "yǒu" },
  { hanzi: "父", pinyin: "fù" },
  { hanzi: "母", pinyin: "mǔ" },
  { hanzi: "女", pinyin: "nǚ" },
  { hanzi: "男", pinyin: "nán" },
  { hanzi: "师", pinyin: "shī" },
  { hanzi: "生", pinyin: "shēng" },
  { hanzi: "校", pinyin: "xiào" },
  { hanzi: "水", pinyin: "shuǐ" },
  { hanzi: "火", pinyin: "huǒ" },
  { hanzi: "车", pinyin: "chē" },
  { hanzi: "飞", pinyin: "fēi" },
  { hanzi: "机", pinyin: "jī" },
  { hanzi: "店", pinyin: "diàn" },
  { hanzi: "医", pinyin: "yī" },
  { hanzi: "院", pinyin: "yuàn" },
  { hanzi: "钱", pinyin: "qián" },
  { hanzi: "块", pinyin: "kuài" },
  { hanzi: "岁", pinyin: "suì" },
]

// HSK 2 Vocabulary (150 words - building on HSK 1)
export const hsk2Words: HanziWord[] = [
  { hanzi: "因", pinyin: "yīn" },
  { hanzi: "所", pinyin: "suǒ" },
  { hanzi: "但", pinyin: "dàn" },
  { hanzi: "虽", pinyin: "suī" },
  { hanzi: "然", pinyin: "rán" },
  { hanzi: "如", pinyin: "rú" },
  { hanzi: "果", pinyin: "guǒ" },
  { hanzi: "或", pinyin: "huò" },
  { hanzi: "者", pinyin: "zhě" },
  { hanzi: "已", pinyin: "yǐ" },
  { hanzi: "经", pinyin: "jīng" },
  { hanzi: "正", pinyin: "zhèng" },
  { hanzi: "真", pinyin: "zhēn" },
  { hanzi: "最", pinyin: "zuì" },
  { hanzi: "更", pinyin: "gèng" },
  { hanzi: "比", pinyin: "bǐ" },
  { hanzi: "第", pinyin: "dì" },
  { hanzi: "每", pinyin: "měi" },
  { hanzi: "次", pinyin: "cì" },
  { hanzi: "别", pinyin: "bié" },
  { hanzi: "让", pinyin: "ràng" },
  { hanzi: "给", pinyin: "g��i" },
  { hanzi: "从", pinyin: "cóng" },
  { hanzi: "向", pinyin: "xiàng" },
  { hanzi: "往", pinyin: "wǎng" },
  { hanzi: "离", pinyin: "lí" },
  { hanzi: "近", pinyin: "jìn" },
  { hanzi: "远", pinyin: "yuǎn" },
  { hanzi: "左", pinyin: "zuǒ" },
  { hanzi: "右", pinyin: "yòu" },
  { hanzi: "旁", pinyin: "páng" },
  { hanzi: "边", pinyin: "biān" },
  { hanzi: "间", pinyin: "jiān" },
  { hanzi: "房", pinyin: "fáng" },
  { hanzi: "门", pinyin: "mén" },
  { hanzi: "窗", pinyin: "chuāng" },
  { hanzi: "桌", pinyin: "zhuō" },
  { hanzi: "椅", pinyin: "yǐ" },
  { hanzi: "床", pinyin: "chuáng" },
  { hanzi: "路", pinyin: "lù" },
  { hanzi: "街", pinyin: "jiē" },
  { hanzi: "城", pinyin: "chéng" },
  { hanzi: "市", pinyin: "shì" },
  { hanzi: "公", pinyin: "gōng" },
  { hanzi: "司", pinyin: "sī" },
  { hanzi: "工", pinyin: "gōng" },
  { hanzi: "作", pinyin: "zuò" },
  { hanzi: "忙", pinyin: "máng" },
  { hanzi: "累", pinyin: "lèi" },
  { hanzi: "快", pinyin: "kuài" },
  { hanzi: "慢", pinyin: "màn" },
  { hanzi: "早", pinyin: "zǎo" },
  { hanzi: "晚", pinyin: "wǎn" },
  { hanzi: "午", pinyin: "wǔ" },
  { hanzi: "晴", pinyin: "qíng" },
  { hanzi: "阴", pinyin: "yīn" },
  { hanzi: "雨", pinyin: "yǔ" },
  { hanzi: "雪", pinyin: "xuě" },
  { hanzi: "冷", pinyin: "lěng" },
  { hanzi: "热", pinyin: "rè" },
  { hanzi: "春", pinyin: "chūn" },
  { hanzi: "夏", pinyin: "xià" },
  { hanzi: "秋", pinyin: "qiū" },
  { hanzi: "冬", pinyin: "dōng" },
  { hanzi: "黑", pinyin: "hēi" },
  { hanzi: "白", pinyin: "bái" },
  { hanzi: "红", pinyin: "hóng" },
  { hanzi: "黄", pinyin: "huáng" },
  { hanzi: "蓝", pinyin: "lán" },
  { hanzi: "绿", pinyin: "lǜ" },
  { hanzi: "穿", pinyin: "chuān" },
  { hanzi: "衣", pinyin: "yī" },
  { hanzi: "服", pinyin: "fú" },
  { hanzi: "裤", pinyin: "kù" },
  { hanzi: "鞋", pinyin: "xié" },
  { hanzi: "帽", pinyin: "mào" },
  { hanzi: "眼", pinyin: "yǎn" },
  { hanzi: "睛", pinyin: "jīng" },
  { hanzi: "耳", pinyin: "ěr" },
  { hanzi: "鼻", pinyin: "bí" },
  { hanzi: "嘴", pinyin: "zuǐ" },
  { hanzi: "脸", pinyin: "liǎn" },
  { hanzi: "身", pinyin: "shēn" },
  { hanzi: "体", pinyin: "tǐ" },
  { hanzi: "脚", pinyin: "jiǎo" },
  { hanzi: "腿", pinyin: "tuǐ" },
  { hanzi: "病", pinyin: "bìng" },
  { hanzi: "药", pinyin: "yào" },
  { hanzi: "疼", pinyin: "téng" },
  { hanzi: "饿", pinyin: "è" },
  { hanzi: "渴", pinyin: "kě" },
  { hanzi: "饱", pinyin: "bǎo" },
  { hanzi: "米", pinyin: "mǐ" },
  { hanzi: "饭", pinyin: "fàn" },
  { hanzi: "菜", pinyin: "cài" },
  { hanzi: "肉", pinyin: "ròu" },
  { hanzi: "鱼", pinyin: "yú" },
  { hanzi: "鸡", pinyin: "jī" },
  { hanzi: "蛋", pinyin: "dàn" },
  { hanzi: "茶", pinyin: "chá" },
  { hanzi: "咖", pinyin: "kā" },
  { hanzi: "啡", pinyin: "fēi" },
  { hanzi: "牛", pinyin: "niú" },
  { hanzi: "奶", pinyin: "nǎi" },
  { hanzi: "苹", pinyin: "píng" },
  { hanzi: "香", pinyin: "xiāng" },
  { hanzi: "蕉", pinyin: "jiāo" },
  { hanzi: "西", pinyin: "xī" },
  { hanzi: "瓜", pinyin: "guā" },
  { hanzi: "帮", pinyin: "bāng" },
  { hanzi: "助", pinyin: "zhù" },
  { hanzi: "问", pinyin: "wèn" },
  { hanzi: "题", pinyin: "tí" },
  { hanzi: "答", pinyin: "dá" },
  { hanzi: "告", pinyin: "gào" },
  { hanzi: "诉", pinyin: "sù" },
  { hanzi: "懂", pinyin: "dǒng" },
  { hanzi: "介", pinyin: "jiè" },
  { hanzi: "绍", pinyin: "shào" },
  { hanzi: "认", pinyin: "rèn" },
  { hanzi: "识", pinyin: "shí" },
  { hanzi: "希", pinyin: "xī" },
  { hanzi: "望", pinyin: "wàng" },
  { hanzi: "觉", pinyin: "jué" },
  { hanzi: "意", pinyin: "yì" },
  { hanzi: "思", pinyin: "sī" },
  { hanzi: "准", pinyin: "zhǔn" },
  { hanzi: "备", pinyin: "bèi" },
  { hanzi: "完", pinyin: "wán" },
  { hanzi: "成", pinyin: "chéng" },
  { hanzi: "开", pinyin: "kāi" },
  { hanzi: "始", pinyin: "shǐ" },
  { hanzi: "结", pinyin: "jié" },
  { hanzi: "束", pinyin: "shù" },
  { hanzi: "运", pinyin: "yùn" },
  { hanzi: "动", pinyin: "dòng" },
  { hanzi: "打", pinyin: "dǎ" },
  { hanzi: "球", pinyin: "qiú" },
  { hanzi: "游", pinyin: "yóu" },
  { hanzi: "泳", pinyin: "yǒng" },
  { hanzi: "唱", pinyin: "chàng" },
  { hanzi: "歌", pinyin: "gē" },
  { hanzi: "跳", pinyin: "tiào" },
  { hanzi: "舞", pinyin: "wǔ" },
  { hanzi: "玩", pinyin: "wán" },
  { hanzi: "旅", pinyin: "lǚ" },
  { hanzi: "行", pinyin: "xíng" },
]

// HSK 3 Vocabulary (300 words - more complex)
export const hsk3Words: HanziWord[] = [
  { hanzi: "世", pinyin: "shì" },
  { hanzi: "界", pinyin: "jiè" },
  { hanzi: "历", pinyin: "lì" },
  { hanzi: "史", pinyin: "shǐ" },
  { hanzi: "文", pinyin: "wén" },
  { hanzi: "化", pinyin: "huà" },
  { hanzi: "社", pinyin: "shè" },
  { hanzi: "政", pinyin: "zhèng" },
  { hanzi: "治", pinyin: "zhì" },
  { hanzi: "济", pinyin: "jì" },
  { hanzi: "科", pinyin: "kē" },
  { hanzi: "技", pinyin: "jì" },
  { hanzi: "术", pinyin: "shù" },
  { hanzi: "教", pinyin: "jiào" },
  { hanzi: "育", pinyin: "yù" },
  { hanzi: "艺", pinyin: "yì" },
  { hanzi: "音", pinyin: "yīn" },
  { hanzi: "乐", pinyin: "yuè" },
  { hanzi: "画", pinyin: "huà" },
  { hanzi: "影", pinyin: "yǐng" },
  { hanzi: "视", pinyin: "shì" },
  { hanzi: "剧", pinyin: "jù" },
  { hanzi: "报", pinyin: "bào" },
  { hanzi: "纸", pinyin: "zhǐ" },
  { hanzi: "杂", pinyin: "zá" },
  { hanzi: "志", pinyin: "zhì" },
  { hanzi: "网", pinyin: "wǎng" },
  { hanzi: "络", pinyin: "luò" },
  { hanzi: "电", pinyin: "diàn" },
  { hanzi: "脑", pinyin: "nǎo" },
  { hanzi: "手", pinyin: "shǒu" },
  { hanzi: "照", pinyin: "zhào" },
  { hanzi: "相", pinyin: "xiāng" },
  { hanzi: "片", pinyin: "piàn" },
  { hanzi: "信", pinyin: "xìn" },
  { hanzi: "息", pinyin: "xī" },
  { hanzi: "消", pinyin: "xiāo" },
  { hanzi: "新", pinyin: "xīn" },
  { hanzi: "闻", pinyin: "wén" },
  { hanzi: "节", pinyin: "jié" },
  { hanzi: "目", pinyin: "mù" },
  { hanzi: "广", pinyin: "guǎng" },
  { hanzi: "播", pinyin: "bō" },
  { hanzi: "环", pinyin: "huán" },
  { hanzi: "境", pinyin: "jìng" },
  { hanzi: "保", pinyin: "bǎo" },
  { hanzi: "护", pinyin: "hù" },
  { hanzi: "污", pinyin: "wū" },
  { hanzi: "染", pinyin: "rǎn" },
  { hanzi: "空", pinyin: "kōng" },
  { hanzi: "气", pinyin: "qì" },
  { hanzi: "资", pinyin: "zī" },
  { hanzi: "源", pinyin: "yuán" },
  { hanzi: "能", pinyin: "néng" },
  { hanzi: "植", pinyin: "zhí" },
  { hanzi: "物", pinyin: "wù" },
  { hanzi: "森", pinyin: "sēn" },
  { hanzi: "林", pinyin: "lín" },
  { hanzi: "海", pinyin: "hǎi" },
  { hanzi: "洋", pinyin: "yáng" },
  { hanzi: "河", pinyin: "hé" },
  { hanzi: "湖", pinyin: "hú" },
  { hanzi: "山", pinyin: "shān" },
  { hanzi: "岛", pinyin: "dǎo" },
  { hanzi: "陆", pinyin: "lù" },
  { hanzi: "洲", pinyin: "zhōu" },
  { hanzi: "亚", pinyin: "yà" },
  { hanzi: "欧", pinyin: "ōu" },
  { hanzi: "非", pinyin: "fēi" },
  { hanzi: "美", pinyin: "měi" },
  { hanzi: "澳", pinyin: "ào" },
  { hanzi: "东", pinyin: "dōng" },
  { hanzi: "南", pinyin: "nán" },
  { hanzi: "北", pinyin: "běi" },
  { hanzi: "际", pinyin: "jì" },
  { hanzi: "关", pinyin: "guān" },
  { hanzi: "系", pinyin: "xì" },
  { hanzi: "交", pinyin: "jiāo" },
  { hanzi: "流", pinyin: "liú" },
  { hanzi: "合", pinyin: "hé" },
  { hanzi: "组", pinyin: "zǔ" },
  { hanzi: "织", pinyin: "zhī" },
  { hanzi: "协", pinyin: "xié" },
  { hanzi: "议", pinyin: "yì" },
  { hanzi: "规", pinyin: "guī" },
  { hanzi: "则", pinyin: "zé" },
  { hanzi: "法", pinyin: "fǎ" },
  { hanzi: "律", pinyin: "lǜ" },
  { hanzi: "权", pinyin: "quán" },
  { hanzi: "利", pinyin: "lì" },
  { hanzi: "义", pinyin: "yì" },
  { hanzi: "务", pinyin: "wù" },
  { hanzi: "责", pinyin: "zé" },
  { hanzi: "任", pinyin: "rèn" },
  { hanzi: "安", pinyin: "ān" },
  { hanzi: "全", pinyin: "quán" },
  { hanzi: "危", pinyin: "wēi" },
  { hanzi: "险", pinyin: "xiǎn" },
  { hanzi: "健", pinyin: "jiàn" },
  { hanzi: "康", pinyin: "kāng" },
  { hanzi: "医", pinyin: "yī" },
  { hanzi: "疗", pinyin: "liáo" },
  { hanzi: "检", pinyin: "jiǎn" },
  { hanzi: "查", pinyin: "chá" },
  { hanzi: "治", pinyin: "zhì" },
  { hanzi: "感", pinyin: "gǎn" },
  { hanzi: "冒", pinyin: "mào" },
  { hanzi: "发", pinyin: "fā" },
  { hanzi: "烧", pinyin: "shāo" },
  { hanzi: "咳", pinyin: "ké" },
  { hanzi: "嗽", pinyin: "sòu" },
  { hanzi: "头", pinyin: "tóu" },
  { hanzi: "痛", pinyin: "tòng" },
  { hanzi: "胃", pinyin: "wèi" },
  { hanzi: "肚", pinyin: "dù" },
  { hanzi: "针", pinyin: "zhēn" },
  { hanzi: "注", pinyin: "zhù" },
  { hanzi: "射", pinyin: "shè" },
  { hanzi: "手", pinyin: "shǒu" },
  { hanzi: "术", pinyin: "shù" },
  { hanzi: "住", pinyin: "zhù" },
  { hanzi: "院", pinyin: "yuàn" },
  { hanzi: "护", pinyin: "hù" },
  { hanzi: "士", pinyin: "shì" },
  { hanzi: "挂", pinyin: "guà" },
  { hanzi: "号", pinyin: "hào" },
  { hanzi: "预", pinyin: "yù" },
  { hanzi: "约", pinyin: "yuē" },
  { hanzi: "紧", pinyin: "jǐn" },
  { hanzi: "急", pinyin: "jí" },
  { hanzi: "救", pinyin: "jiù" },
  { hanzi: "护", pinyin: "hù" },
  { hanzi: "商", pinyin: "shāng" },
  { hanzi: "业", pinyin: "yè" },
  { hanzi: "贸", pinyin: "mào" },
  { hanzi: "易", pinyin: "yì" },
  { hanzi: "进", pinyin: "jìn" },
  { hanzi: "口", pinyin: "kǒu" },
  { hanzi: "出", pinyin: "chū" },
  { hanzi: "产", pinyin: "chǎn" },
  { hanzi: "品", pinyin: "pǐn" },
  { hanzi: "质", pinyin: "zhì" },
  { hanzi: "量", pinyin: "liàng" },
  { hanzi: "价", pinyin: "jià" },
  { hanzi: "格", pinyin: "gé" },
  { hanzi: "便", pinyin: "pián" },
  { hanzi: "宜", pinyin: "yí" },
  { hanzi: "贵", pinyin: "guì" },
  { hanzi: "折", pinyin: "zhé" },
  { hanzi: "扣", pinyin: "kòu" },
  { hanzi: "免", pinyin: "miǎn" },
  { hanzi: "费", pinyin: "fèi" },
  { hanzi: "付", pinyin: "fù" },
  { hanzi: "款", pinyin: "kuǎn" },
  { hanzi: "现", pinyin: "xiàn" },
  { hanzi: "金", pinyin: "jīn" },
  { hanzi: "卡", pinyin: "kǎ" },
  { hanzi: "账", pinyin: "zhàng" },
  { hanzi: "户", pinyin: "hù" },
  { hanzi: "银", pinyin: "yín" },
  { hanzi: "取", pinyin: "qǔ" },
  { hanzi: "存", pinyin: "cún" },
  { hanzi: "转", pinyin: "zhuǎn" },
  { hanzi: "汇", pinyin: "huì" },
  { hanzi: "率", pinyin: "lǜ" },
  { hanzi: "投", pinyin: "tóu" },
  { hanzi: "股", pinyin: "gǔ" },
  { hanzi: "票", pinyin: "piào" },
  { hanzi: "基", pinyin: "jī" },
  { hanzi: "债", pinyin: "zhài" },
  { hanzi: "券", pinyin: "quàn" },
  { hanzi: "保", pinyin: "bǎo" },
  { hanzi: "险", pinyin: "xiǎn" },
  { hanzi: "退", pinyin: "tuì" },
  { hanzi: "休", pinyin: "xiū" },
  { hanzi: "养", pinyin: "yǎng" },
  { hanzi: "老", pinyin: "lǎo" },
  { hanzi: "职", pinyin: "zhí" },
  { hanzi: "位", pinyin: "wèi" },
  { hanzi: "薪", pinyin: "xīn" },
  { hanzi: "资", pinyin: "zī" },
  { hanzi: "奖", pinyin: "jiǎng" },
  { hanzi: "励", pinyin: "lì" },
  { hanzi: "升", pinyin: "shēng" },
  { hanzi: "降", pinyin: "jiàng" },
  { hanzi: "调", pinyin: "diào" },
  { hanzi: "聘", pinyin: "pìn" },
  { hanzi: "辞", pinyin: "cí" },
  { hanzi: "面", pinyin: "miàn" },
  { hanzi: "试", pinyin: "shì" },
  { hanzi: "简", pinyin: "jiǎn" },
  { hanzi: "历", pinyin: "lì" },
  { hanzi: "经", pinyin: "jīng" },
  { hanzi: "验", pinyin: "yàn" },
  { hanzi: "能", pinyin: "néng" },
  { hanzi: "力", pinyin: "lì" },
  { hanzi: "才", pinyin: "cái" },
  { hanzi: "华", pinyin: "huá" },
  { hanzi: "专", pinyin: "zhuān" },
  { hanzi: "长", pinyin: "cháng" },
  { hanzi: "优", pinyin: "yōu" },
  { hanzi: "秀", pinyin: "xiù" },
  { hanzi: "积", pinyin: "jī" },
  { hanzi: "极", pinyin: "jí" },
  { hanzi: "努", pinyin: "nǔ" },
  { hanzi: "勤", pinyin: "qín" },
  { hanzi: "奋", pinyin: "fèn" },
  { hanzi: "斗", pinyin: "dòu" },
  { hanzi: "坚", pinyin: "jiān" },
  { hanzi: "持", pinyin: "chí" },
  { hanzi: "耐", pinyin: "nài" },
  { hanzi: "诚", pinyin: "chéng" },
  { hanzi: "实", pinyin: "shí" },
  { hanzi: "谦", pinyin: "qiān" },
  { hanzi: "虚", pinyin: "xū" },
  { hanzi: "礼", pinyin: "lǐ" },
  { hanzi: "貌", pinyin: "mào" },
  { hanzi: "尊", pinyin: "zūn" },
  { hanzi: "重", pinyin: "zhòng" },
  { hanzi: "友", pinyin: "yǒu" },
  { hanzi: "善", pinyin: "shàn" },
  { hanzi: "热", pinyin: "rè" },
  { hanzi: "情", pinyin: "qíng" },
  { hanzi: "冷", pinyin: "lěng" },
  { hanzi: "淡", pinyin: "dàn" },
  { hanzi: "严", pinyin: "yán" },
  { hanzi: "肃", pinyin: "sù" },
  { hanzi: "温", pinyin: "wēn" },
  { hanzi: "柔", pinyin: "róu" },
  { hanzi: "幽", pinyin: "yōu" },
  { hanzi: "默", pinyin: "mò" },
  { hanzi: "活", pinyin: "huó" },
  { hanzi: "泼", pinyin: "pō" },
  { hanzi: "开", pinyin: "kāi" },
  { hanzi: "朗", pinyin: "lǎng" },
  { hanzi: "内", pinyin: "nèi" },
  { hanzi: "向", pinyin: "xiàng" },
  { hanzi: "敏", pinyin: "mǐn" },
  { hanzi: "感", pinyin: "gǎn" },
  { hanzi: "固", pinyin: "gù" },
  { hanzi: "执", pinyin: "zhí" },
  { hanzi: "灵", pinyin: "líng" },
  { hanzi: "顽", pinyin: "wán" },
  { hanzi: "皮", pinyin: "pí" },
  { hanzi: "聪", pinyin: "cōng" },
  { hanzi: "明", pinyin: "míng" },
  { hanzi: "糊", pinyin: "hú" },
  { hanzi: "涂", pinyin: "tú" },
  { hanzi: "马", pinyin: "mǎ" },
  { hanzi: "虎", pinyin: "hǔ" },
  { hanzi: "细", pinyin: "xì" },
  { hanzi: "心", pinyin: "xīn" },
  { hanzi: "粗", pinyin: "cū" },
  { hanzi: "急", pinyin: "jí" },
  { hanzi: "躁", pinyin: "zào" },
  { hanzi: "冲", pinyin: "chōng" },
  { hanzi: "沉", pinyin: "chén" },
  { hanzi: "稳", pinyin: "wěn" },
  { hanzi: "勇", pinyin: "yǒng" },
  { hanzi: "敢", pinyin: "gǎn" },
  { hanzi: "胆", pinyin: "dǎn" },
  { hanzi: "怕", pinyin: "pà" },
  { hanzi: "害", pinyin: "hài" },
  { hanzi: "骄", pinyin: "jiāo" },
  { hanzi: "傲", pinyin: "ào" },
  { hanzi: "自", pinyin: "zì" },
  { hanzi: "卑", pinyin: "bēi" },
  { hanzi: "信", pinyin: "xìn" },
  { hanzi: "满", pinyin: "mǎn" },
  { hanzi: "足", pinyin: "zú" },
  { hanzi: "贪", pinyin: "tān" },
  { hanzi: "婪", pinyin: "lán" },
  { hanzi: "吝", pinyin: "lìn" },
  { hanzi: "啬", pinyin: "sè" },
  { hanzi: "慷", pinyin: "kāng" },
  { hanzi: "慨", pinyin: "kǎi" },
  { hanzi: "乐", pinyin: "lè" },
  { hanzi: "观", pinyin: "guān" },
  { hanzi: "悲", pinyin: "bēi" },
  { hanzi: "伤", pinyin: "shāng" },
  { hanzi: "郁", pinyin: "yù" },
  { hanzi: "闷", pinyin: "mèn" },
  { hanzi: "焦", pinyin: "jiāo" },
  { hanzi: "虑", pinyin: "lǜ" },
  { hanzi: "恐", pinyin: "kǒng" },
  { hanzi: "惧", pinyin: "jù" },
  { hanzi: "愤", pinyin: "fèn" },
  { hanzi: "怒", pinyin: "nù" },
  { hanzi: "嫉", pinyin: "jí" },
  { hanzi: "妒", pinyin: "dù" },
  { hanzi: "羡", pinyin: "xiàn" },
  { hanzi: "慕", pinyin: "mù" },
  { hanzi: "崇", pinyin: "chóng" },
  { hanzi: "拜", pinyin: "bài" },
  { hanzi: "厌", pinyin: "yàn" },
  { hanzi: "恶", pinyin: "è" },
  { hanzi: "反", pinyin: "fǎn" },
  { hanzi: "对", pinyin: "duì" },
  { hanzi: "赞", pinyin: "zàn" },
  { hanzi: "同", pinyin: "tóng" },
  { hanzi: "怀", pinyin: "huái" },
  { hanzi: "疑", pinyin: "yí" },
  { hanzi: "肯", pinyin: "kěn" },
  { hanzi: "定", pinyin: "dìng" },
  { hanzi: "否", pinyin: "fǒu" },
  { hanzi: "犹", pinyin: "yóu" },
  { hanzi: "豫", pinyin: "yù" },
  { hanzi: "决", pinyin: "jué" },
  { hanzi: "绝", pinyin: "jué" },
  { hanzi: "放", pinyin: "fàng" },
  { hanzi: "弃", pinyin: "qì" },
  { hanzi: "选", pinyin: "xuǎn" },
  { hanzi: "择", pinyin: "zé" },
  { hanzi: "判", pinyin: "pàn" },
  { hanzi: "断", pinyin: "duàn" },
  { hanzi: "评", pinyin: "píng" },
  { hanzi: "价", pinyin: "jià" },
]

// HSK 4 Vocabulary (600 words - advanced)
export const hsk4Words: HanziWord[] = [
  ...hsk3Words,
  { hanzi: "抽", pinyin: "chōu" },
  { hanzi: "象", pinyin: "xiàng" },
  { hanzi: "具", pinyin: "jù" },
  { hanzi: "概", pinyin: "gài" },
  { hanzi: "念", pinyin: "niàn" },
  { hanzi: "理", pinyin: "lǐ" },
  { hanzi: "论", pinyin: "lùn" },
  { hanzi: "假", pinyin: "jiǎ" },
  { hanzi: "设", pinyin: "shè" },
  { hanzi: "推", pinyin: "tuī" },
  { hanzi: "测", pinyin: "cè" },
  { hanzi: "证", pinyin: "zhèng" },
  { hanzi: "据", pinyin: "jù" },
  { hanzi: "论", pinyin: "lùn" },
  { hanzi: "述", pinyin: "shù" },
  { hanzi: "描", pinyin: "miáo" },
  { hanzi: "写", pinyin: "xiě" },
  { hanzi: "叙", pinyin: "xù" },
  { hanzi: "说", pinyin: "shuō" },
  { hanzi: "解", pinyin: "jiě" },
  { hanzi: "释", pinyin: "shì" },
  { hanzi: "定", pinyin: "dìng" },
  { hanzi: "义", pinyin: "yì" },
  { hanzi: "分", pinyin: "fēn" },
  { hanzi: "类", pinyin: "lèi" },
  { hanzi: "比", pinyin: "bǐ" },
  { hanzi: "较", pinyin: "jiào" },
  { hanzi: "对", pinyin: "duì" },
  { hanzi: "比", pinyin: "bǐ" },
  { hanzi: "区", pinyin: "qū" },
  { hanzi: "别", pinyin: "bié" },
  { hanzi: "联", pinyin: "lián" },
  { hanzi: "系", pinyin: "xì" },
  { hanzi: "影", pinyin: "yǐng" },
  { hanzi: "响", pinyin: "xiǎng" },
  { hanzi: "因", pinyin: "yīn" },
  { hanzi: "素", pinyin: "sù" },
  { hanzi: "原", pinyin: "yuán" },
  { hanzi: "因", pinyin: "yīn" },
  { hanzi: "结", pinyin: "jié" },
  { hanzi: "果", pinyin: "guǒ" },
  { hanzi: "目", pinyin: "mù" },
  { hanzi: "的", pinyin: "dì" },
  { hanzi: "手", pinyin: "shǒu" },
  { hanzi: "段", pinyin: "duàn" },
  { hanzi: "方", pinyin: "fāng" },
  { hanzi: "法", pinyin: "fǎ" },
  { hanzi: "过", pinyin: "guò" },
  { hanzi: "程", pinyin: "chéng" },
  { hanzi: "步", pinyin: "bù" },
  { hanzi: "骤", pinyin: "zhòu" },
  { hanzi: "阶", pinyin: "jiē" },
  { hanzi: "段", pinyin: "duàn" },
  { hanzi: "环", pinyin: "huán" },
  { hanzi: "节", pinyin: "jié" },
  { hanzi: "部", pinyin: "bù" },
  { hanzi: "分", pinyin: "fēn" },
  { hanzi: "整", pinyin: "zhěng" },
  { hanzi: "体", pinyin: "tǐ" },
  { hanzi: "总", pinyin: "zǒng" },
  { hanzi: "局", pinyin: "jú" },
  { hanzi: "角", pinyin: "jiǎo" },
  { hanzi: "度", pinyin: "dù" },
  { hanzi: "层", pinyin: "céng" },
  { hanzi: "次", pinyin: "cì" },
  { hanzi: "范", pinyin: "fàn" },
  { hanzi: "围", pinyin: "wéi" },
  { hanzi: "领", pinyin: "lǐng" },
  { hanzi: "域", pinyin: "yù" },
  { hanzi: "背", pinyin: "bèi" },
  { hanzi: "景", pinyin: "jǐng" },
  { hanzi: "条", pinyin: "tiáo" },
  { hanzi: "件", pinyin: "jiàn" },
  { hanzi: "前", pinyin: "qián" },
  { hanzi: "提", pinyin: "tí" },
  { hanzi: "基", pinyin: "jī" },
  { hanzi: "础", pinyin: "chǔ" },
  { hanzi: "核", pinyin: "hé" },
  { hanzi: "心", pinyin: "xīn" },
  { hanzi: "关", pinyin: "guān" },
  { hanzi: "键", pinyin: "jiàn" },
  { hanzi: "重", pinyin: "zhòng" },
  { hanzi: "点", pinyin: "diǎn" },
  { hanzi: "难", pinyin: "nán" },
  { hanzi: "要", pinyin: "yào" },
  { hanzi: "特", pinyin: "tè" },
  { hanzi: "征", pinyin: "zhēng" },
  { hanzi: "属", pinyin: "shǔ" },
  { hanzi: "性", pinyin: "xìng" },
  { hanzi: "功", pinyin: "gōng" },
  { hanzi: "能", pinyin: "néng" },
  { hanzi: "作", pinyin: "zuò" },
  { hanzi: "用", pinyin: "yòng" },
  { hanzi: "价", pinyin: "jià" },
  { hanzi: "值", pinyin: "zhí" },
  { hanzi: "意", pinyin: "yì" },
  { hanzi: "义", pinyin: "yì" },
  { hanzi: "地", pinyin: "dì" },
  { hanzi: "位", pinyin: "wèi" },
  { hanzi: "状", pinyin: "zhuàng" },
  { hanzi: "态", pinyin: "tài" },
  { hanzi: "趋", pinyin: "qū" },
  { hanzi: "势", pinyin: "shì" },
  { hanzi: "变", pinyin: "biàn" },
  { hanzi: "化", pinyin: "huà" },
  { hanzi: "发", pinyin: "fā" },
  { hanzi: "展", pinyin: "zhǎn" },
  { hanzi: "改", pinyin: "gǎi" },
  { hanzi: "革", pinyin: "gé" },
  { hanzi: "创", pinyin: "chuàng" },
  { hanzi: "新", pinyin: "xīn" },
  { hanzi: "突", pinyin: "tū" },
  { hanzi: "破", pinyin: "pò" },
  { hanzi: "进", pinyin: "jìn" },
  { hanzi: "步", pinyin: "bù" },
  { hanzi: "提", pinyin: "tí" },
  { hanzi: "高", pinyin: "gāo" },
  { hanzi: "增", pinyin: "zēng" },
  { hanzi: "加", pinyin: "jiā" },
  { hanzi: "减", pinyin: "jiǎn" },
  { hanzi: "少", pinyin: "shǎo" },
  { hanzi: "扩", pinyin: "kuò" },
  { hanzi: "大", pinyin: "dà" },
  { hanzi: "缩", pinyin: "suō" },
  { hanzi: "小", pinyin: "xiǎo" },
  { hanzi: "加", pinyin: "jiā" },
  { hanzi: "强", pinyin: "qiáng" },
  { hanzi: "削", pinyin: "xuē" },
  { hanzi: "弱", pinyin: "ruò" },
  { hanzi: "促", pinyin: "cù" },
  { hanzi: "进", pinyin: "jìn" },
  { hanzi: "阻", pinyin: "zǔ" },
  { hanzi: "碍", pinyin: "ài" },
  { hanzi: "支", pinyin: "zhī" },
  { hanzi: "持", pinyin: "chí" },
  { hanzi: "反", pinyin: "fǎn" },
  { hanzi: "对", pinyin: "duì" },
  { hanzi: "鼓", pinyin: "gǔ" },
  { hanzi: "励", pinyin: "lì" },
  { hanzi: "批", pinyin: "pī" },
  { hanzi: "评", pinyin: "píng" },
  { hanzi: "表", pinyin: "biǎo" },
  { hanzi: "扬", pinyin: "yáng" },
  { hanzi: "惩", pinyin: "chéng" },
  { hanzi: "罚", pinyin: "fá" },
  { hanzi: "奖", pinyin: "jiǎng" },
  { hanzi: "赏", pinyin: "shǎng" },
  { hanzi: "激", pinyin: "jī" },
  { hanzi: "励", pinyin: "lì" },
  { hanzi: "约", pinyin: "yuē" },
  { hanzi: "束", pinyin: "shù" },
  { hanzi: "限", pinyin: "xiàn" },
  { hanzi: "制", pinyin: "zhì" },
  { hanzi: "控", pinyin: "kòng" },
  { hanzi: "制", pinyin: "zhì" },
  { hanzi: "管", pinyin: "guǎn" },
  { hanzi: "理", pinyin: "lǐ" },
  { hanzi: "监", pinyin: "jiān" },
  { hanzi: "督", pinyin: "dū" },
  { hanzi: "指", pinyin: "zhǐ" },
  { hanzi: "导", pinyin: "d��o" },
  { hanzi: "领", pinyin: "lǐng" },
  { hanzi: "导", pinyin: "dǎo" },
  { hanzi: "组", pinyin: "zǔ" },
  { hanzi: "织", pinyin: "zhī" },
  { hanzi: "协", pinyin: "xié" },
  { hanzi: "调", pinyin: "diào" },
  { hanzi: "沟", pinyin: "gōu" },
  { hanzi: "通", pinyin: "tōng" },
  { hanzi: "配", pinyin: "pèi" },
  { hanzi: "合", pinyin: "hé" },
  { hanzi: "合", pinyin: "hé" },
  { hanzi: "作", pinyin: "zuò" },
  { hanzi: "竞", pinyin: "jìng" },
  { hanzi: "争", pinyin: "zhēng" },
  { hanzi: "妥", pinyin: "tuǒ" },
  { hanzi: "协", pinyin: "xié" },
  { hanzi: "谈", pinyin: "tán" },
  { hanzi: "判", pinyin: "pàn" },
  { hanzi: "讨", pinyin: "tǎo" },
  { hanzi: "论", pinyin: "lùn" },
  { hanzi: "辩", pinyin: "biàn" },
  { hanzi: "论", pinyin: "lùn" },
  { hanzi: "争", pinyin: "zhēng" },
  { hanzi: "议", pinyin: "yì" },
  { hanzi: "分", pinyin: "fēn" },
  { hanzi: "歧", pinyin: "qí" },
  { hanzi: "矛", pinyin: "máo" },
  { hanzi: "盾", pinyin: "dùn" },
  { hanzi: "冲", pinyin: "chōng" },
  { hanzi: "突", pinyin: "tū" },
  { hanzi: "纠", pinyin: "jiū" },
  { hanzi: "纷", pinyin: "fēn" },
  { hanzi: "和", pinyin: "hé" },
  { hanzi: "解", pinyin: "jiě" },
  { hanzi: "调", pinyin: "tiáo" },
  { hanzi: "解", pinyin: "jiě" },
  { hanzi: "仲", pinyin: "zhòng" },
  { hanzi: "裁", pinyin: "cái" },
  { hanzi: "诉", pinyin: "sù" },
  { hanzi: "讼", pinyin: "s��ng" },
  { hanzi: "审", pinyin: "shěn" },
  { hanzi: "判", pinyin: "pàn" },
  { hanzi: "裁", pinyin: "cái" },
  { hanzi: "决", pinyin: "jué" },
  { hanzi: "执", pinyin: "zhí" },
  { hanzi: "行", pinyin: "xíng" },
  { hanzi: "实", pinyin: "shí" },
  { hanzi: "施", pinyin: "shī" },
  { hanzi: "贯", pinyin: "guàn" },
  { hanzi: "彻", pinyin: "chè" },
  { hanzi: "落", pinyin: "luò" },
  { hanzi: "实", pinyin: "shí" },
  { hanzi: "推", pinyin: "tuī" },
  { hanzi: "行", pinyin: "xíng" },
  { hanzi: "推", pinyin: "tuī" },
  { hanzi: "广", pinyin: "guǎng" },
  { hanzi: "普", pinyin: "pǔ" },
  { hanzi: "及", pinyin: "jí" },
  { hanzi: "传", pinyin: "chuán" },
  { hanzi: "播", pinyin: "bō" },
  { hanzi: "宣", pinyin: "xuān" },
  { hanzi: "传", pinyin: "chuán" },
  { hanzi: "倡", pinyin: "chàng" },
  { hanzi: "导", pinyin: "dǎo" },
  { hanzi: "提", pinyin: "tí" },
  { hanzi: "倡", pinyin: "chàng" },
  { hanzi: "呼", pinyin: "hū" },
  { hanzi: "吁", pinyin: "yù" },
  { hanzi: "号", pinyin: "hào" },
  { hanzi: "召", pinyin: "zhào" },
  { hanzi: "动", pinyin: "dòng" },
  { hanzi: "员", pinyin: "yuán" },
  { hanzi: "发", pinyin: "fā" },
  { hanzi: "动", pinyin: "dòng" },
  { hanzi: "启", pinyin: "qǐ" },
  { hanzi: "发", pinyin: "fā" },
  { hanzi: "激", pinyin: "jī" },
  { hanzi: "发", pinyin: "fā" },
  { hanzi: "引", pinyin: "yǐn" },
  { hanzi: "导", pinyin: "dǎo" },
  { hanzi: "引", pinyin: "yǐn" },
  { hanzi: "起", pinyin: "qǐ" },
  { hanzi: "导", pinyin: "dǎo" },
  { hanzi: "致", pinyin: "zhì" },
  { hanzi: "造", pinyin: "zào" },
  { hanzi: "成", pinyin: "chéng" },
  { hanzi: "形", pinyin: "xíng" },
  { hanzi: "成", pinyin: "chéng" },
  { hanzi: "产", pinyin: "chǎn" },
  { hanzi: "生", pinyin: "shēng" },
  { hanzi: "出", pinyin: "chū" },
  { hanzi: "现", pinyin: "xiàn" },
  { hanzi: "发", pinyin: "fā" },
  { hanzi: "生", pinyin: "shēng" },
  { hanzi: "存", pinyin: "cún" },
  { hanzi: "在", pinyin: "zài" },
  { hanzi: "消", pinyin: "xiāo" },
  { hanzi: "失", pinyin: "shī" },
  { hanzi: "持", pinyin: "chí" },
  { hanzi: "续", pinyin: "xù" },
  { hanzi: "维", pinyin: "wéi" },
  { hanzi: "持", pinyin: "chí" },
  { hanzi: "保", pinyin: "bǎo" },
  { hanzi: "持", pinyin: "chí" },
  { hanzi: "恢", pinyin: "huī" },
  { hanzi: "复", pinyin: "fù" },
  { hanzi: "重", pinyin: "chóng" },
  { hanzi: "建", pinyin: "jiàn" },
  { hanzi: "建", pinyin: "jiàn" },
  { hanzi: "立", pinyin: "lì" },
  { hanzi: "建", pinyin: "jiàn" },
  { hanzi: "设", pinyin: "shè" },
  { hanzi: "构", pinyin: "gòu" },
  { hanzi: "建", pinyin: "jiàn" },
  { hanzi: "塑", pinyin: "sù" },
  { hanzi: "造", pinyin: "zào" },
  { hanzi: "打", pinyin: "dǎ" },
  { hanzi: "造", pinyin: "zào" },
  { hanzi: "培", pinyin: "péi" },
  { hanzi: "养", pinyin: "yǎng" },
  { hanzi: "培", pinyin: "péi" },
  { hanzi: "育", pinyin: "yù" },
  { hanzi: "发", pinyin: "fā" },
  { hanzi: "掘", pinyin: "jué" },
  { hanzi: "挖", pinyin: "wā" },
  { hanzi: "掘", pinyin: "jué" },
  { hanzi: "探", pinyin: "tàn" },
  { hanzi: "索", pinyin: "suǒ" },
  { hanzi: "研", pinyin: "yán" },
  { hanzi: "究", pinyin: "jiū" },
  { hanzi: "调", pinyin: "diào" },
  { hanzi: "查", pinyin: "chá" },
  { hanzi: "考", pinyin: "kǎo" },
  { hanzi: "察", pinyin: "chá" },
  { hanzi: "分", pinyin: "fēn" },
  { hanzi: "析", pinyin: "xī" },
  { hanzi: "综", pinyin: "zōng" },
  { hanzi: "合", pinyin: "hé" },
  { hanzi: "归", pinyin: "guī" },
  { hanzi: "纳", pinyin: "nà" },
  { hanzi: "演", pinyin: "yǎn" },
  { hanzi: "绎", pinyin: "yì" },
  { hanzi: "推", pinyin: "tuī" },
  { hanzi: "理", pinyin: "lǐ" },
  { hanzi: "计", pinyin: "jì" },
  { hanzi: "算", pinyin: "suàn" },
  { hanzi: "统", pinyin: "tǒng" },
  { hanzi: "计", pinyin: "jì" },
  { hanzi: "预", pinyin: "yù" },
  { hanzi: "测", pinyin: "cè" },
  { hanzi: "估", pinyin: "gū" },
  { hanzi: "计", pinyin: "jì" },
  { hanzi: "评", pinyin: "píng" },
  { hanzi: "估", pinyin: "gū" },
  { hanzi: "衡", pinyin: "héng" },
  { hanzi: "量", pinyin: "liáng" },
  { hanzi: "检", pinyin: "jiǎn" },
  { hanzi: "测", pinyin: "cè" },
  { hanzi: "检", pinyin: "jiǎn" },
  { hanzi: "验", pinyin: "yàn" },
  { hanzi: "试", pinyin: "shì" },
  { hanzi: "验", pinyin: "yàn" },
  { hanzi: "实", pinyin: "shí" },
  { hanzi: "验", pinyin: "yàn" },
  { hanzi: "验", pinyin: "yàn" },
  { hanzi: "证", pinyin: "zhèng" },
  { hanzi: "核", pinyin: "hé" },
  { hanzi: "实", pinyin: "shí" },
  { hanzi: "确", pinyin: "què" },
  { hanzi: "认", pinyin: "rèn" },
  { hanzi: "证", pinyin: "zhèng" },
  { hanzi: "实", pinyin: "shí" },
  { hanzi: "证", pinyin: "zhèng" },
  { hanzi: "明", pinyin: "míng" },
  { hanzi: "表", pinyin: "biǎo" },
  { hanzi: "明", pinyin: "míng" },
  { hanzi: "说", pinyin: "shuō" },
  { hanzi: "明", pinyin: "míng" },
  { hanzi: "阐", pinyin: "chǎn" },
  { hanzi: "明", pinyin: "míng" },
  { hanzi: "阐", pinyin: "chǎn" },
  { hanzi: "述", pinyin: "shù" },
  { hanzi: "阐", pinyin: "chǎn" },
  { hanzi: "释", pinyin: "shì" },
  { hanzi: "解", pinyin: "jiě" },
  { hanzi: "读", pinyin: "dú" },
  { hanzi: "诠", pinyin: "quán" },
  { hanzi: "释", pinyin: "shì" },
  { hanzi: "注", pinyin: "zhù" },
  { hanzi: "解", pinyin: "jiě" },
  { hanzi: "备", pinyin: "bèi" },
  { hanzi: "注", pinyin: "zhù" },
  { hanzi: "标", pinyin: "biāo" },
  { hanzi: "注", pinyin: "zhù" },
  { hanzi: "引", pinyin: "yǐn" },
  { hanzi: "用", pinyin: "yòng" },
  { hanzi: "参", pinyin: "cān" },
  { hanzi: "考", pinyin: "kǎo" },
  { hanzi: "借", pinyin: "jiè" },
  { hanzi: "鉴", pinyin: "jiàn" },
  { hanzi: "吸", pinyin: "xī" },
  { hanzi: "收", pinyin: "shōu" },
  { hanzi: "采", pinyin: "cǎi" },
  { hanzi: "纳", pinyin: "nà" },
  { hanzi: "接", pinyin: "jiē" },
  { hanzi: "受", pinyin: "shòu" },
  { hanzi: "认", pinyin: "rèn" },
  { hanzi: "可", pinyin: "kě" },
  { hanzi: "赞", pinyin: "zàn" },
  { hanzi: "成", pinyin: "chéng" },
  { hanzi: "同", pinyin: "tóng" },
  { hanzi: "意", pinyin: "yì" },
]

export const hskWordsByLevel: Record<HSKLevel, HanziWord[]> = {
  1: hsk1Words,
  2: [...hsk1Words, ...hsk2Words],
  3: [...hsk1Words, ...hsk2Words, ...hsk3Words],
  4: [...hsk1Words, ...hsk2Words, ...hsk4Words],
}

// Common 2-character compound words for each HSK level
export const hsk2CharWords: Record<HSKLevel, HanziWord[]> = {
  1: [
    { hanzi: "你好", pinyin: "nǐ hǎo" },
    { hanzi: "我们", pinyin: "wǒ men" },
    { hanzi: "他们", pinyin: "tā men" },
    { hanzi: "中国", pinyin: "zhōng guó" },
    { hanzi: "朋友", pinyin: "péng yǒu" },
    { hanzi: "学生", pinyin: "xué shēng" },
    { hanzi: "老师", pinyin: "lǎo shī" },
    { hanzi: "学校", pinyin: "xué xiào" },
    { hanzi: "医生", pinyin: "yī shēng" },
    { hanzi: "医院", pinyin: "yī yuàn" },
    { hanzi: "飞机", pinyin: "fēi jī" },
    { hanzi: "今天", pinyin: "jīn tiān" },
    { hanzi: "明天", pinyin: "míng tiān" },
    { hanzi: "现在", pinyin: "xiàn zài" },
    { hanzi: "时候", pinyin: "shí hou" },
    { hanzi: "什么", pinyin: "shén me" },
    { hanzi: "怎么", pinyin: "zěn me" },
    { hanzi: "多少", pinyin: "duō shǎo" },
    { hanzi: "喜欢", pinyin: "xǐ huān" },
    { hanzi: "高兴", pinyin: "gāo xìng" },
    { hanzi: "漂亮", pinyin: "piào liang" },
    { hanzi: "东西", pinyin: "dōng xi" },
    { hanzi: "工作", pinyin: "gōng zuò" },
    { hanzi: "电视", pinyin: "diàn shì" },
    { hanzi: "电脑", pinyin: "diàn nǎo" },
    { hanzi: "手机", pinyin: "shǒu jī" },
    { hanzi: "名字", pinyin: "míng zi" },
    { hanzi: "爸爸", pinyin: "bà ba" },
    { hanzi: "妈妈", pinyin: "mā ma" },
    { hanzi: "哥哥", pinyin: "gē ge" },
    { hanzi: "姐姐", pinyin: "jiě jie" },
    { hanzi: "弟弟", pinyin: "dì di" },
    { hanzi: "妹妹", pinyin: "mèi mei" },
    { hanzi: "再见", pinyin: "zài jiàn" },
    { hanzi: "谢谢", pinyin: "xiè xie" },
    { hanzi: "对不起", pinyin: "duì bu qǐ" },
    { hanzi: "没关系", pinyin: "méi guān xi" },
    { hanzi: "苹果", pinyin: "píng guǒ" },
    { hanzi: "衣服", pinyin: "yī fu" },
    { hanzi: "天气", pinyin: "tiān qì" },
  ],
  2: [
    { hanzi: "小说", pinyin: "xiǎo shuō" },
    { hanzi: "上课", pinyin: "shàng kè" },
    { hanzi: "秋天", pinyin: "qiū tiān" },
    { hanzi: "汉语", pinyin: "hàn yǔ" },
    { hanzi: "晚餐", pinyin: "wǎn cān" },
    { hanzi: "下雨", pinyin: "xià yǔ" },
    { hanzi: "新年", pinyin: "xīn nián" },
    { hanzi: "皮包", pinyin: "pí bāo" },
    { hanzi: "下午", pinyin: "xià wǔ" },
    { hanzi: "准备", pinyin: "zhǔn bèi" },
    { hanzi: "去年", pinyin: "qù nián" },
    { hanzi: "果汁", pinyin: "guǒ zhī" },
    { hanzi: "木头", pinyin: "mù tou" },
    { hanzi: "但是", pinyin: "dàn shì" },
    { hanzi: "重要", pinyin: "zhòng yào" },
    { hanzi: "生活", pinyin: "shēng huó" },
    { hanzi: "语法", pinyin: "yǔ fǎ" },
    { hanzi: "中间", pinyin: "zhōng jiān" },
    { hanzi: "特别", pinyin: "tè bié" },
    { hanzi: "再见", pinyin: "zài jiàn" },
    { hanzi: "好看", pinyin: "hǎo kàn" },
    { hanzi: "永远", pinyin: "yǒng yuǎn" },
    { hanzi: "院子", pinyin: "yuàn zi" },
    { hanzi: "没问", pinyin: "méi wèn" },
    { hanzi: "因为", pinyin: "yīn wèi" },
    { hanzi: "所以", pinyin: "suǒ yǐ" },
    { hanzi: "虽然", pinyin: "suī rán" },
    { hanzi: "如果", pinyin: "rú guǒ" },
    { hanzi: "已经", pinyin: "yǐ jīng" },
    { hanzi: "正在", pinyin: "zhèng zài" },
    { hanzi: "最近", pinyin: "zuì jìn" },
    { hanzi: "公司", pinyin: "gōng sī" },
    { hanzi: "房间", pinyin: "fáng jiān" },
    { hanzi: "城市", pinyin: "chéng shì" },
    { hanzi: "春天", pinyin: "chūn tiān" },
    { hanzi: "夏天", pinyin: "xià tiān" },
    { hanzi: "冬天", pinyin: "dōng tiān" },
    { hanzi: "运动", pinyin: "yùn dòng" },
    { hanzi: "游泳", pinyin: "yóu yǒng" },
    { hanzi: "唱歌", pinyin: "chàng gē" },
    { hanzi: "跳舞", pinyin: "tiào wǔ" },
    { hanzi: "旅行", pinyin: "lǚ xíng" },
    { hanzi: "帮助", pinyin: "bāng zhù" },
    { hanzi: "问题", pinyin: "wèn tí" },
    { hanzi: "介绍", pinyin: "jiè shào" },
    { hanzi: "认识", pinyin: "rèn shi" },
    { hanzi: "希望", pinyin: "xī wàng" },
    { hanzi: "开始", pinyin: "kāi shǐ" },
    { hanzi: "结束", pinyin: "jié shù" },
    { hanzi: "完成", pinyin: "wán chéng" },
  ],
  3: [
    { hanzi: "世界", pinyin: "shì jiè" },
    { hanzi: "历史", pinyin: "lì shǐ" },
    { hanzi: "文化", pinyin: "wén huà" },
    { hanzi: "社会", pinyin: "shè huì" },
    { hanzi: "政治", pinyin: "zhèng zhì" },
    { hanzi: "经济", pinyin: "jīng jì" },
    { hanzi: "科技", pinyin: "kē jì" },
    { hanzi: "教育", pinyin: "jiào yù" },
    { hanzi: "艺术", pinyin: "yì shù" },
    { hanzi: "音乐", pinyin: "yīn yuè" },
    { hanzi: "电影", pinyin: "diàn yǐng" },
    { hanzi: "报纸", pinyin: "bào zhǐ" },
    { hanzi: "杂志", pinyin: "zá zhì" },
    { hanzi: "网络", pinyin: "wǎng luò" },
    { hanzi: "新闻", pinyin: "xīn wén" },
    { hanzi: "环境", pinyin: "huán jìng" },
    { hanzi: "保护", pinyin: "bǎo hù" },
    { hanzi: "污染", pinyin: "wū rǎn" },
    { hanzi: "空气", pinyin: "kōng qì" },
    { hanzi: "资源", pinyin: "zī yuán" },
    { hanzi: "植物", pinyin: "zhí wù" },
    { hanzi: "森林", pinyin: "sēn lín" },
    { hanzi: "海洋", pinyin: "hǎi yáng" },
    { hanzi: "国际", pinyin: "guó jì" },
    { hanzi: "关系", pinyin: "guān xì" },
    { hanzi: "交流", pinyin: "jiāo liú" },
    { hanzi: "组织", pinyin: "zǔ zhī" },
    { hanzi: "法律", pinyin: "fǎ lǜ" },
    { hanzi: "权利", pinyin: "quán lì" },
    { hanzi: "责任", pinyin: "zé rèn" },
    { hanzi: "安全", pinyin: "ān quán" },
    { hanzi: "危险", pinyin: "wēi xiǎn" },
    { hanzi: "健康", pinyin: "jiàn kāng" },
    { hanzi: "医疗", pinyin: "yī liáo" },
    { hanzi: "商业", pinyin: "shāng yè" },
    { hanzi: "贸易", pinyin: "mào yì" },
    { hanzi: "产品", pinyin: "chǎn pǐn" },
    { hanzi: "质量", pinyin: "zhì liàng" },
    { hanzi: "价格", pinyin: "jià gé" },
    { hanzi: "银行", pinyin: "yín háng" },
    { hanzi: "职业", pinyin: "zhí yè" },
    { hanzi: "经验", pinyin: "jīng yàn" },
    { hanzi: "能力", pinyin: "néng lì" },
    { hanzi: "努力", pinyin: "nǔ lì" },
    { hanzi: "坚持", pinyin: "jiān chí" },
    { hanzi: "诚实", pinyin: "chéng shí" },
    { hanzi: "礼貌", pinyin: "lǐ mào" },
    { hanzi: "尊重", pinyin: "zūn zhòng" },
    { hanzi: "热情", pinyin: "rè qíng" },
    { hanzi: "勇敢", pinyin: "yǒng gǎn" },
  ],
  4: [
    { hanzi: "发展", pinyin: "fā zhǎn" },
    { hanzi: "改革", pinyin: "gǎi gé" },
    { hanzi: "创新", pinyin: "chuàng xīn" },
    { hanzi: "竞争", pinyin: "jìng zhēng" },
    { hanzi: "合作", pinyin: "hé zuò" },
    { hanzi: "管理", pinyin: "guǎn lǐ" },
    { hanzi: "计划", pinyin: "jì huà" },
    { hanzi: "目标", pinyin: "mù biāo" },
    { hanzi: "成功", pinyin: "chéng gōng" },
    { hanzi: "失败", pinyin: "shī bài" },
    { hanzi: "机会", pinyin: "jī huì" },
    { hanzi: "挑战", pinyin: "tiǎo zhàn" },
    { hanzi: "困难", pinyin: "kùn nan" },
    { hanzi: "解决", pinyin: "jiě jué" },
    { hanzi: "分析", pinyin: "fēn xī" },
    { hanzi: "研究", pinyin: "yán jiū" },
    { hanzi: "讨论", pinyin: "tǎo lùn" },
    { hanzi: "交流", pinyin: "jiāo liú" },
    { hanzi: "沟通", pinyin: "gōu tōng" },
    { hanzi: "表达", pinyin: "biǎo dá" },
    { hanzi: "理解", pinyin: "lǐ jiě" },
    { hanzi: "支持", pinyin: "zhī chí" },
    { hanzi: "反对", pinyin: "fǎn duì" },
    { hanzi: "同意", pinyin: "tóng yì" },
    { hanzi: "建议", pinyin: "jiàn yì" },
    { hanzi: "意见", pinyin: "yì jiàn" },
    { hanzi: "决定", pinyin: "jué dìng" },
    { hanzi: "选择", pinyin: "xuǎn zé" },
    { hanzi: "影响", pinyin: "yǐng xiǎng" },
    { hanzi: "结果", pinyin: "jié guǒ" },
    { hanzi: "原因", pinyin: "yuán yīn" },
    { hanzi: "目的", pinyin: "mù dì" },
    { hanzi: "方法", pinyin: "fāng fǎ" },
    { hanzi: "过程", pinyin: "guò chéng" },
    { hanzi: "情况", pinyin: "qíng kuàng" },
    { hanzi: "条件", pinyin: "tiáo jiàn" },
    { hanzi: "标准", pinyin: "biāo zhǔn" },
    { hanzi: "原则", pinyin: "yuán zé" },
    { hanzi: "态度", pinyin: "tài du" },
    { hanzi: "观点", pinyin: "guān diǎn" },
    { hanzi: "思想", pinyin: "sī xiǎng" },
    { hanzi: "知识", pinyin: "zhī shi" },
    { hanzi: "技术", pinyin: "jì shù" },
    { hanzi: "水平", pinyin: "shuǐ píng" },
    { hanzi: "程度", pinyin: "chéng dù" },
    { hanzi: "范围", pinyin: "fàn wéi" },
    { hanzi: "内容", pinyin: "nèi róng" },
    { hanzi: "形式", pinyin: "xíng shì" },
    { hanzi: "特点", pinyin: "tè diǎn" },
    { hanzi: "性质", pinyin: "xìng zhì" },
  ],
}

export function generateWordSet(level: HSKLevel, count: number = 100): HanziWord[] {
  // Use 2-character compound words
  const wordPool = hsk2CharWords[level]
  const words: HanziWord[] = []
  while (words.length < count) {
    const randomIndex = Math.floor(Math.random() * wordPool.length)
    words.push(wordPool[randomIndex])
  }
  return words
}
